package SourcePackage;

import Clases.alumno;
import Clases.docente;
import Clases.usuario;
import Clases.ControladorUsuario;

import java.text.SimpleDateFormat;
import java.util.HashSet;
import javax.swing.JOptionPane;

public class ConsultarUsuarios extends javax.swing.JInternalFrame {

    /**
     * Creates new form RegistroCliente1
     */
    public ConsultarUsuarios() {
        initComponents();
    //    jTextFieldInstituto.setVisible(false);
     //   jLabel7.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setTitle("Consultar Usuarios");
        setToolTipText("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 307, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 414, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
